-- good-looking-web T3: editable sessions in D1 (ADR-0003, ADR-0004, ADR-0006, ADR-0008).
-- Promoted to vocab-photo-api/migrations/0001_sessions.sql; revert with
-- vocab-photo-api/migrations/down/0001_sessions.sql.
--
-- Revisions: each session has one counter (`sessions.rev`) that goes up with
-- every write; every cell, tombstone and arrived photo stores the session
-- revision it last changed at. The change feed (ADR-0005) is "everything of this
-- session whose revision is above N" — no separate change log.
-- Times are ISO-8601 UTC strings, as in the KV documents they replace.

-- One published list. `id` is the link id; `expires_at` is fixed at the first
-- publish and kept on republish (D4). `edit_token_hash` is the SHA-256 of the
-- republish token (ADR-0008) and is NULL for a link imported from KV, which has
-- no token. A republish raises `rev` and sets `replaced_rev` to it, so a page
-- whose cursor is below `replaced_rev` reloads the whole list.
CREATE TABLE sessions (
  id              TEXT    PRIMARY KEY,
  created_at      TEXT    NOT NULL,
  expires_at      TEXT    NOT NULL,
  rev             INTEGER NOT NULL DEFAULT 0 CHECK (rev >= 0),
  replaced_rev    INTEGER NOT NULL DEFAULT 0 CHECK (replaced_rev >= 0),
  detail          TEXT    NOT NULL DEFAULT 'translation'
                          CHECK (detail IN ('translation', 'definition', 'both')),
  edit_token_hash TEXT
);

-- Daily clean-up: "sessions past expires_at".
CREATE INDEX sessions_expires_at_idx ON sessions (expires_at);

-- One row of a session's table. `id` is generated by whoever adds the row (the
-- app at publish, a page's plus button — ADR-0004), so it is unique only within
-- its session. Each cell carries the session revision of its last change; a
-- save applies only while the cell is still at the revision the client saw.
-- A deleted row stays as a tombstone: `deleted_at_rev` is the revision of the
-- delete, NULL while the row is live. `source_id` links a recognised row to its
-- photo slot (ADR-0006), NULL for a typed row or a publish without photos.
CREATE TABLE rows (
  session_id      TEXT    NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
  id              TEXT    NOT NULL,
  position        INTEGER NOT NULL,
  source_id       TEXT,
  word            TEXT    NOT NULL DEFAULT '',
  word_rev        INTEGER NOT NULL DEFAULT 0,
  translation     TEXT    NOT NULL DEFAULT '',
  translation_rev INTEGER NOT NULL DEFAULT 0,
  definition      TEXT    NOT NULL DEFAULT '',
  definition_rev  INTEGER NOT NULL DEFAULT 0,
  deleted_at_rev  INTEGER,
  PRIMARY KEY (session_id, id)
);

-- Change feed: "rows of a session changed after rev N". The query must use this
-- exact expression to hit the index:
--   WHERE session_id = ?1
--     AND max(word_rev, translation_rev, definition_rev, coalesce(deleted_at_rev, 0)) > ?2
CREATE INDEX rows_changed_idx ON rows (
  session_id,
  max(word_rev, translation_rev, definition_rev, coalesce(deleted_at_rev, 0))
);

-- Rendering the page and the AnkiDroid file in table order.
CREATE INDEX rows_position_idx ON rows (session_id, position);

-- A photo slot declared at publish (ADR-0006): "pending" until the app uploads
-- its bytes, then "arrived" at `arrived_rev` so polling pages swap the
-- placeholder for the photo. `media_type` and `bytes` are known only once the
-- bytes arrive. The bytes themselves live in R2 (`SOURCES`), never here.
CREATE TABLE sources (
  session_id      TEXT    NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
  id              TEXT    NOT NULL,
  ord             INTEGER NOT NULL,
  media_type      TEXT,
  bytes           INTEGER CHECK (bytes IS NULL OR bytes >= 0),
  status          TEXT    NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'arrived')),
  arrived_rev     INTEGER,
  PRIMARY KEY (session_id, id),
  CHECK ((status = 'arrived') = (arrived_rev IS NOT NULL))
);

-- Change feed: photos of a session that arrived after rev N.
CREATE INDEX sources_arrived_idx ON sources (session_id, arrived_rev);

-- Definition autofill: one page's allowance per UTC day (AC-18). `utc_day` is
-- 'YYYY-MM-DD'. Incremented only while below the limit.
CREATE TABLE page_autofill (
  session_id      TEXT    NOT NULL REFERENCES sessions (id) ON DELETE CASCADE,
  utc_day         TEXT    NOT NULL,
  used            INTEGER NOT NULL DEFAULT 0 CHECK (used >= 0),
  PRIMARY KEY (session_id, utc_day)
);

-- Definition autofill: the share of the dictionary quota all pages together
-- may use per UTC day (AC-18b). Not tied to a session, so it survives clean-up.
CREATE TABLE all_pages_autofill (
  utc_day         TEXT    PRIMARY KEY,
  used            INTEGER NOT NULL DEFAULT 0 CHECK (used >= 0)
);
